### PR TITLE
Adding the start setup

### PR DESCRIPTION
**Pull request by iMartinDav**
# Description
-Create the app of rails 
-Add postgresql database

### CODE REVIEW

**Comment by GustavoHiguera** [comment]
Good luck with the project!

**Comment by dagp-ucol** [comment]
Approved Commit - Initial Commit

**Review by GustavoHiguera — APPROVED** [review]
Good luck!

**Review by elioflo — COMMENTED** [review]
Looks good to me

**Review by dagp-ucol — APPROVED** [review]

**Pull request merged**
